version: '3.7'

services:
  redis:
    hostname: redis
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    hostname: postgres
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  worker:
    build:
      context: ./parcels-web-app
      dockerfile: Dockerfile
    container_name: worker
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
#    command: celery -A app.app_tasks.tasks.celery worker -l info

  web:
    build:
      context: ./parcels-web-app
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - postgres
      - redis
    env_file:
      - "./parcels-web-app/.env"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ./parcels-web-app/boot.sh
